/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectRouteImport } from './routes/$subject'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AnatomyRouteImport } from './routes/anatomy'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ArticlesDebugRouteImport } from './routes/articles-debug'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BiologicalProcessesRouteImport } from './routes/biological-processes'
import { Route as BiotechnologyRouteImport } from './routes/biotechnology'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CellsMicroscopyRouteImport } from './routes/cells-microscopy'
import { Route as CustomListsRouteImport } from './routes/custom-lists'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EcologyEnvironmentRouteImport } from './routes/ecology-environment'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GeneticsDnaRouteImport } from './routes/genetics-dna'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HumanBiologyRouteImport } from './routes/human-biology'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as OrganismsRouteImport } from './routes/organisms'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as PhotosyntheseRouteImport } from './routes/photosynthese'
import { Route as PhotosynthesisRouteImport } from './routes/photosynthesis'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SectionTopicRouteImport } from './routes/$section.$topic'
import { Route as SubjectSectionRouteImport } from './routes/$subject.$section'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiSeedHeroSlidesRouteImport } from './routes/api/seed-hero-slides'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ArticlesCellularRespirationRouteImport } from './routes/articles.cellular-respiration'
import { Route as ArticlesEnzymeCatalysisRouteImport } from './routes/articles.enzyme-catalysis'
import { Route as ArticlesEvolutionNaturalSelectionRouteImport } from './routes/articles.evolution-natural-selection'
import { Route as ArticlesFoodChainsEnergyFlowRouteImport } from './routes/articles.food-chains-energy-flow'
import { Route as ArticlesHumanAnatomySystemsRouteImport } from './routes/articles.human-anatomy-systems'
import { Route as ArticlesMeiosisGameteFormationRouteImport } from './routes/articles.meiosis-gamete-formation'
import { Route as ArticlesMitosisCellDivisionRouteImport } from './routes/articles.mitosis-cell-division'
import { Route as ArticlesPhotosynthesisLightReactionsRouteImport } from './routes/articles.photosynthesis-light-reactions'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as TutorialsSlugRouteImport } from './routes/tutorials.$slug'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as SubjectSectionTopicRouteImport } from './routes/$subject.$section.$topic'
import { Route as AuthenticatedAdminArticlesRouteImport } from './routes/_authenticated/admin.articles'
import { Route as AuthenticatedAdminHeroSlidesRouteImport } from './routes/_authenticated/admin.hero-slides'
import { Route as AuthenticatedAdminNavLinksRouteImport } from './routes/_authenticated/admin.nav-links'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminPagesListRouteImport } from './routes/_authenticated/admin.pages-list'
import { Route as AuthenticatedAdminSectionsRouteImport } from './routes/_authenticated/admin.sections'
import { Route as AuthenticatedAdminTopicsRouteImport } from './routes/_authenticated/admin.topics'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as ApiAtlasGenerateRouteImport } from './routes/api/atlas.generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectRoute = SubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyRoute = AnatomyRouteImport.update({
  id: '/anatomy',
  path: '/anatomy',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesDebugRoute = ArticlesDebugRouteImport.update({
  id: '/articles-debug',
  path: '/articles-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BiologicalProcessesRoute = BiologicalProcessesRouteImport.update({
  id: '/biological-processes',
  path: '/biological-processes',
  getParentRoute: () => rootRouteImport,
} as any)
const BiotechnologyRoute = BiotechnologyRouteImport.update({
  id: '/biotechnology',
  path: '/biotechnology',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsMicroscopyRoute = CellsMicroscopyRouteImport.update({
  id: '/cells-microscopy',
  path: '/cells-microscopy',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomListsRoute = CustomListsRouteImport.update({
  id: '/custom-lists',
  path: '/custom-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EcologyEnvironmentRoute = EcologyEnvironmentRouteImport.update({
  id: '/ecology-environment',
  path: '/ecology-environment',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticsDnaRoute = GeneticsDnaRouteImport.update({
  id: '/genetics-dna',
  path: '/genetics-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanBiologyRoute = HumanBiologyRouteImport.update({
  id: '/human-biology',
  path: '/human-biology',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganismsRoute = OrganismsRouteImport.update({
  id: '/organisms',
  path: '/organisms',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosyntheseRoute = PhotosyntheseRouteImport.update({
  id: '/photosynthese',
  path: '/photosynthese',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosynthesisRoute = PhotosynthesisRouteImport.update({
  id: '/photosynthesis',
  path: '/photosynthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionTopicRoute = SectionTopicRouteImport.update({
  id: '/$section/$topic',
  path: '/$section/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSectionRoute = SubjectSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SubjectRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSeedHeroSlidesRoute = ApiSeedHeroSlidesRouteImport.update({
  id: '/api/seed-hero-slides',
  path: '/api/seed-hero-slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesCellularRespirationRoute =
  ArticlesCellularRespirationRouteImport.update({
    id: '/cellular-respiration',
    path: '/cellular-respiration',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesEnzymeCatalysisRoute = ArticlesEnzymeCatalysisRouteImport.update({
  id: '/enzyme-catalysis',
  path: '/enzyme-catalysis',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesEvolutionNaturalSelectionRoute =
  ArticlesEvolutionNaturalSelectionRouteImport.update({
    id: '/evolution-natural-selection',
    path: '/evolution-natural-selection',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesFoodChainsEnergyFlowRoute =
  ArticlesFoodChainsEnergyFlowRouteImport.update({
    id: '/food-chains-energy-flow',
    path: '/food-chains-energy-flow',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesHumanAnatomySystemsRoute =
  ArticlesHumanAnatomySystemsRouteImport.update({
    id: '/human-anatomy-systems',
    path: '/human-anatomy-systems',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesMeiosisGameteFormationRoute =
  ArticlesMeiosisGameteFormationRouteImport.update({
    id: '/meiosis-gamete-formation',
    path: '/meiosis-gamete-formation',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesMitosisCellDivisionRoute =
  ArticlesMitosisCellDivisionRouteImport.update({
    id: '/mitosis-cell-division',
    path: '/mitosis-cell-division',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPhotosynthesisLightReactionsRoute =
  ArticlesPhotosynthesisLightReactionsRouteImport.update({
    id: '/photosynthesis-light-reactions',
    path: '/photosynthesis-light-reactions',
    getParentRoute: () => ArticlesRoute,
  } as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const TutorialsSlugRoute = TutorialsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TutorialsRoute,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VideosRoute,
} as any)
const SubjectSectionTopicRoute = SubjectSectionTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => SubjectSectionRoute,
} as any)
const AuthenticatedAdminArticlesRoute =
  AuthenticatedAdminArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHeroSlidesRoute =
  AuthenticatedAdminHeroSlidesRouteImport.update({
    id: '/hero-slides',
    path: '/hero-slides',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNavLinksRoute =
  AuthenticatedAdminNavLinksRouteImport.update({
    id: '/nav-links',
    path: '/nav-links',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPagesListRoute =
  AuthenticatedAdminPagesListRouteImport.update({
    id: '/pages-list',
    path: '/pages-list',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectionsRoute =
  AuthenticatedAdminSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTopicsRoute =
  AuthenticatedAdminTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAtlasGenerateRoute = ApiAtlasGenerateRouteImport.update({
  id: '/api/atlas/generate',
  path: '/api/atlas/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/ai': typeof AiRoute
  '/anatomy': typeof AnatomyRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/articles-debug': typeof ArticlesDebugRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/biological-processes': typeof BiologicalProcessesRoute
  '/biotechnology': typeof BiotechnologyRoute
  '/categories': typeof CategoriesRoute
  '/cells-microscopy': typeof CellsMicroscopyRoute
  '/custom-lists': typeof CustomListsRoute
  '/download': typeof DownloadRoute
  '/ecology-environment': typeof EcologyEnvironmentRoute
  '/evolution': typeof EvolutionRoute
  '/flashcards': typeof FlashcardsRoute
  '/genetics-dna': typeof GeneticsDnaRoute
  '/glossary': typeof GlossaryRoute
  '/human-biology': typeof HumanBiologyRoute
  '/notebook': typeof NotebookRoute
  '/organisms': typeof OrganismsRoute
  '/pages': typeof PagesRouteWithChildren
  '/photosynthese': typeof PhotosyntheseRoute
  '/photosynthesis': typeof PhotosynthesisRoute
  '/plants': typeof PlantsRoute
  '/quizzes': typeof QuizzesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/$section/$topic': typeof SectionTopicRoute
  '/$subject/$section': typeof SubjectSectionRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/seed-hero-slides': typeof ApiSeedHeroSlidesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/cellular-respiration': typeof ArticlesCellularRespirationRoute
  '/articles/enzyme-catalysis': typeof ArticlesEnzymeCatalysisRoute
  '/articles/evolution-natural-selection': typeof ArticlesEvolutionNaturalSelectionRoute
  '/articles/food-chains-energy-flow': typeof ArticlesFoodChainsEnergyFlowRoute
  '/articles/human-anatomy-systems': typeof ArticlesHumanAnatomySystemsRoute
  '/articles/meiosis-gamete-formation': typeof ArticlesMeiosisGameteFormationRoute
  '/articles/mitosis-cell-division': typeof ArticlesMitosisCellDivisionRoute
  '/articles/photosynthesis-light-reactions': typeof ArticlesPhotosynthesisLightReactionsRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/$subject/$section/$topic': typeof SubjectSectionTopicRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/nav-links': typeof AuthenticatedAdminNavLinksRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/pages-list': typeof AuthenticatedAdminPagesListRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/api/atlas/generate': typeof ApiAtlasGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRouteWithChildren
  '/ai': typeof AiRoute
  '/anatomy': typeof AnatomyRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/articles-debug': typeof ArticlesDebugRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/biological-processes': typeof BiologicalProcessesRoute
  '/biotechnology': typeof BiotechnologyRoute
  '/categories': typeof CategoriesRoute
  '/cells-microscopy': typeof CellsMicroscopyRoute
  '/custom-lists': typeof CustomListsRoute
  '/download': typeof DownloadRoute
  '/ecology-environment': typeof EcologyEnvironmentRoute
  '/evolution': typeof EvolutionRoute
  '/flashcards': typeof FlashcardsRoute
  '/genetics-dna': typeof GeneticsDnaRoute
  '/glossary': typeof GlossaryRoute
  '/human-biology': typeof HumanBiologyRoute
  '/notebook': typeof NotebookRoute
  '/organisms': typeof OrganismsRoute
  '/pages': typeof PagesRouteWithChildren
  '/photosynthese': typeof PhotosyntheseRoute
  '/photosynthesis': typeof PhotosynthesisRoute
  '/plants': typeof PlantsRoute
  '/quizzes': typeof QuizzesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/$section/$topic': typeof SectionTopicRoute
  '/$subject/$section': typeof SubjectSectionRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/seed-hero-slides': typeof ApiSeedHeroSlidesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/cellular-respiration': typeof ArticlesCellularRespirationRoute
  '/articles/enzyme-catalysis': typeof ArticlesEnzymeCatalysisRoute
  '/articles/evolution-natural-selection': typeof ArticlesEvolutionNaturalSelectionRoute
  '/articles/food-chains-energy-flow': typeof ArticlesFoodChainsEnergyFlowRoute
  '/articles/human-anatomy-systems': typeof ArticlesHumanAnatomySystemsRoute
  '/articles/meiosis-gamete-formation': typeof ArticlesMeiosisGameteFormationRoute
  '/articles/mitosis-cell-division': typeof ArticlesMitosisCellDivisionRoute
  '/articles/photosynthesis-light-reactions': typeof ArticlesPhotosynthesisLightReactionsRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/$subject/$section/$topic': typeof SubjectSectionTopicRoute
  '/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/admin/nav-links': typeof AuthenticatedAdminNavLinksRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/pages-list': typeof AuthenticatedAdminPagesListRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/api/atlas/generate': typeof ApiAtlasGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$subject': typeof SubjectRouteWithChildren
  '/ai': typeof AiRoute
  '/anatomy': typeof AnatomyRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/articles-debug': typeof ArticlesDebugRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/biological-processes': typeof BiologicalProcessesRoute
  '/biotechnology': typeof BiotechnologyRoute
  '/categories': typeof CategoriesRoute
  '/cells-microscopy': typeof CellsMicroscopyRoute
  '/custom-lists': typeof CustomListsRoute
  '/download': typeof DownloadRoute
  '/ecology-environment': typeof EcologyEnvironmentRoute
  '/evolution': typeof EvolutionRoute
  '/flashcards': typeof FlashcardsRoute
  '/genetics-dna': typeof GeneticsDnaRoute
  '/glossary': typeof GlossaryRoute
  '/human-biology': typeof HumanBiologyRoute
  '/notebook': typeof NotebookRoute
  '/organisms': typeof OrganismsRoute
  '/pages': typeof PagesRouteWithChildren
  '/photosynthese': typeof PhotosyntheseRoute
  '/photosynthesis': typeof PhotosynthesisRoute
  '/plants': typeof PlantsRoute
  '/quizzes': typeof QuizzesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timeline': typeof TimelineRoute
  '/tutorials': typeof TutorialsRouteWithChildren
  '/videos': typeof VideosRouteWithChildren
  '/$section/$topic': typeof SectionTopicRoute
  '/$subject/$section': typeof SubjectSectionRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/seed-hero-slides': typeof ApiSeedHeroSlidesRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/cellular-respiration': typeof ArticlesCellularRespirationRoute
  '/articles/enzyme-catalysis': typeof ArticlesEnzymeCatalysisRoute
  '/articles/evolution-natural-selection': typeof ArticlesEvolutionNaturalSelectionRoute
  '/articles/food-chains-energy-flow': typeof ArticlesFoodChainsEnergyFlowRoute
  '/articles/human-anatomy-systems': typeof ArticlesHumanAnatomySystemsRoute
  '/articles/meiosis-gamete-formation': typeof ArticlesMeiosisGameteFormationRoute
  '/articles/mitosis-cell-division': typeof ArticlesMitosisCellDivisionRoute
  '/articles/photosynthesis-light-reactions': typeof ArticlesPhotosynthesisLightReactionsRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/tutorials/$slug': typeof TutorialsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/$subject/$section/$topic': typeof SubjectSectionTopicRoute
  '/_authenticated/admin/articles': typeof AuthenticatedAdminArticlesRoute
  '/_authenticated/admin/hero-slides': typeof AuthenticatedAdminHeroSlidesRoute
  '/_authenticated/admin/nav-links': typeof AuthenticatedAdminNavLinksRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/pages-list': typeof AuthenticatedAdminPagesListRoute
  '/_authenticated/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/_authenticated/admin/topics': typeof AuthenticatedAdminTopicsRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/api/atlas/generate': typeof ApiAtlasGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$subject'
    | '/ai'
    | '/anatomy'
    | '/articles'
    | '/articles-debug'
    | '/atlas'
    | '/auth'
    | '/biological-processes'
    | '/biotechnology'
    | '/categories'
    | '/cells-microscopy'
    | '/custom-lists'
    | '/download'
    | '/ecology-environment'
    | '/evolution'
    | '/flashcards'
    | '/genetics-dna'
    | '/glossary'
    | '/human-biology'
    | '/notebook'
    | '/organisms'
    | '/pages'
    | '/photosynthese'
    | '/photosynthesis'
    | '/plants'
    | '/quizzes'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/tutorials'
    | '/videos'
    | '/$section/$topic'
    | '/$subject/$section'
    | '/admin'
    | '/dashboard'
    | '/api/seed-hero-slides'
    | '/articles/$slug'
    | '/articles/cellular-respiration'
    | '/articles/enzyme-catalysis'
    | '/articles/evolution-natural-selection'
    | '/articles/food-chains-energy-flow'
    | '/articles/human-anatomy-systems'
    | '/articles/meiosis-gamete-formation'
    | '/articles/mitosis-cell-division'
    | '/articles/photosynthesis-light-reactions'
    | '/pages/$slug'
    | '/tutorials/$slug'
    | '/videos/$slug'
    | '/$subject/$section/$topic'
    | '/admin/articles'
    | '/admin/hero-slides'
    | '/admin/nav-links'
    | '/admin/pages'
    | '/admin/pages-list'
    | '/admin/sections'
    | '/admin/topics'
    | '/admin/videos'
    | '/api/atlas/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$subject'
    | '/ai'
    | '/anatomy'
    | '/articles'
    | '/articles-debug'
    | '/atlas'
    | '/auth'
    | '/biological-processes'
    | '/biotechnology'
    | '/categories'
    | '/cells-microscopy'
    | '/custom-lists'
    | '/download'
    | '/ecology-environment'
    | '/evolution'
    | '/flashcards'
    | '/genetics-dna'
    | '/glossary'
    | '/human-biology'
    | '/notebook'
    | '/organisms'
    | '/pages'
    | '/photosynthese'
    | '/photosynthesis'
    | '/plants'
    | '/quizzes'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/tutorials'
    | '/videos'
    | '/$section/$topic'
    | '/$subject/$section'
    | '/admin'
    | '/dashboard'
    | '/api/seed-hero-slides'
    | '/articles/$slug'
    | '/articles/cellular-respiration'
    | '/articles/enzyme-catalysis'
    | '/articles/evolution-natural-selection'
    | '/articles/food-chains-energy-flow'
    | '/articles/human-anatomy-systems'
    | '/articles/meiosis-gamete-formation'
    | '/articles/mitosis-cell-division'
    | '/articles/photosynthesis-light-reactions'
    | '/pages/$slug'
    | '/tutorials/$slug'
    | '/videos/$slug'
    | '/$subject/$section/$topic'
    | '/admin/articles'
    | '/admin/hero-slides'
    | '/admin/nav-links'
    | '/admin/pages'
    | '/admin/pages-list'
    | '/admin/sections'
    | '/admin/topics'
    | '/admin/videos'
    | '/api/atlas/generate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$subject'
    | '/ai'
    | '/anatomy'
    | '/articles'
    | '/articles-debug'
    | '/atlas'
    | '/auth'
    | '/biological-processes'
    | '/biotechnology'
    | '/categories'
    | '/cells-microscopy'
    | '/custom-lists'
    | '/download'
    | '/ecology-environment'
    | '/evolution'
    | '/flashcards'
    | '/genetics-dna'
    | '/glossary'
    | '/human-biology'
    | '/notebook'
    | '/organisms'
    | '/pages'
    | '/photosynthese'
    | '/photosynthesis'
    | '/plants'
    | '/quizzes'
    | '/reset-password'
    | '/saved'
    | '/settings'
    | '/signup'
    | '/timeline'
    | '/tutorials'
    | '/videos'
    | '/$section/$topic'
    | '/$subject/$section'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/api/seed-hero-slides'
    | '/articles/$slug'
    | '/articles/cellular-respiration'
    | '/articles/enzyme-catalysis'
    | '/articles/evolution-natural-selection'
    | '/articles/food-chains-energy-flow'
    | '/articles/human-anatomy-systems'
    | '/articles/meiosis-gamete-formation'
    | '/articles/mitosis-cell-division'
    | '/articles/photosynthesis-light-reactions'
    | '/pages/$slug'
    | '/tutorials/$slug'
    | '/videos/$slug'
    | '/$subject/$section/$topic'
    | '/_authenticated/admin/articles'
    | '/_authenticated/admin/hero-slides'
    | '/_authenticated/admin/nav-links'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/pages-list'
    | '/_authenticated/admin/sections'
    | '/_authenticated/admin/topics'
    | '/_authenticated/admin/videos'
    | '/api/atlas/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SubjectRoute: typeof SubjectRouteWithChildren
  AiRoute: typeof AiRoute
  AnatomyRoute: typeof AnatomyRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ArticlesDebugRoute: typeof ArticlesDebugRoute
  AtlasRoute: typeof AtlasRoute
  AuthRoute: typeof AuthRoute
  BiologicalProcessesRoute: typeof BiologicalProcessesRoute
  BiotechnologyRoute: typeof BiotechnologyRoute
  CategoriesRoute: typeof CategoriesRoute
  CellsMicroscopyRoute: typeof CellsMicroscopyRoute
  CustomListsRoute: typeof CustomListsRoute
  DownloadRoute: typeof DownloadRoute
  EcologyEnvironmentRoute: typeof EcologyEnvironmentRoute
  EvolutionRoute: typeof EvolutionRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GeneticsDnaRoute: typeof GeneticsDnaRoute
  GlossaryRoute: typeof GlossaryRoute
  HumanBiologyRoute: typeof HumanBiologyRoute
  NotebookRoute: typeof NotebookRoute
  OrganismsRoute: typeof OrganismsRoute
  PagesRoute: typeof PagesRouteWithChildren
  PhotosyntheseRoute: typeof PhotosyntheseRoute
  PhotosynthesisRoute: typeof PhotosynthesisRoute
  PlantsRoute: typeof PlantsRoute
  QuizzesRoute: typeof QuizzesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TimelineRoute: typeof TimelineRoute
  TutorialsRoute: typeof TutorialsRouteWithChildren
  VideosRoute: typeof VideosRouteWithChildren
  SectionTopicRoute: typeof SectionTopicRoute
  ApiSeedHeroSlidesRoute: typeof ApiSeedHeroSlidesRoute
  ApiAtlasGenerateRoute: typeof ApiAtlasGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject': {
      id: '/$subject'
      path: '/$subject'
      fullPath: '/$subject'
      preLoaderRoute: typeof SubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy': {
      id: '/anatomy'
      path: '/anatomy'
      fullPath: '/anatomy'
      preLoaderRoute: typeof AnatomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles-debug': {
      id: '/articles-debug'
      path: '/articles-debug'
      fullPath: '/articles-debug'
      preLoaderRoute: typeof ArticlesDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biological-processes': {
      id: '/biological-processes'
      path: '/biological-processes'
      fullPath: '/biological-processes'
      preLoaderRoute: typeof BiologicalProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biotechnology': {
      id: '/biotechnology'
      path: '/biotechnology'
      fullPath: '/biotechnology'
      preLoaderRoute: typeof BiotechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells-microscopy': {
      id: '/cells-microscopy'
      path: '/cells-microscopy'
      fullPath: '/cells-microscopy'
      preLoaderRoute: typeof CellsMicroscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-lists': {
      id: '/custom-lists'
      path: '/custom-lists'
      fullPath: '/custom-lists'
      preLoaderRoute: typeof CustomListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecology-environment': {
      id: '/ecology-environment'
      path: '/ecology-environment'
      fullPath: '/ecology-environment'
      preLoaderRoute: typeof EcologyEnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetics-dna': {
      id: '/genetics-dna'
      path: '/genetics-dna'
      fullPath: '/genetics-dna'
      preLoaderRoute: typeof GeneticsDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-biology': {
      id: '/human-biology'
      path: '/human-biology'
      fullPath: '/human-biology'
      preLoaderRoute: typeof HumanBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisms': {
      id: '/organisms'
      path: '/organisms'
      fullPath: '/organisms'
      preLoaderRoute: typeof OrganismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photosynthese': {
      id: '/photosynthese'
      path: '/photosynthese'
      fullPath: '/photosynthese'
      preLoaderRoute: typeof PhotosyntheseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photosynthesis': {
      id: '/photosynthesis'
      path: '/photosynthesis'
      fullPath: '/photosynthesis'
      preLoaderRoute: typeof PhotosynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$topic': {
      id: '/$section/$topic'
      path: '/$section/$topic'
      fullPath: '/$section/$topic'
      preLoaderRoute: typeof SectionTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject/$section': {
      id: '/$subject/$section'
      path: '/$section'
      fullPath: '/$subject/$section'
      preLoaderRoute: typeof SubjectSectionRouteImport
      parentRoute: typeof SubjectRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/seed-hero-slides': {
      id: '/api/seed-hero-slides'
      path: '/api/seed-hero-slides'
      fullPath: '/api/seed-hero-slides'
      preLoaderRoute: typeof ApiSeedHeroSlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/cellular-respiration': {
      id: '/articles/cellular-respiration'
      path: '/cellular-respiration'
      fullPath: '/articles/cellular-respiration'
      preLoaderRoute: typeof ArticlesCellularRespirationRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/enzyme-catalysis': {
      id: '/articles/enzyme-catalysis'
      path: '/enzyme-catalysis'
      fullPath: '/articles/enzyme-catalysis'
      preLoaderRoute: typeof ArticlesEnzymeCatalysisRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/evolution-natural-selection': {
      id: '/articles/evolution-natural-selection'
      path: '/evolution-natural-selection'
      fullPath: '/articles/evolution-natural-selection'
      preLoaderRoute: typeof ArticlesEvolutionNaturalSelectionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/food-chains-energy-flow': {
      id: '/articles/food-chains-energy-flow'
      path: '/food-chains-energy-flow'
      fullPath: '/articles/food-chains-energy-flow'
      preLoaderRoute: typeof ArticlesFoodChainsEnergyFlowRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/human-anatomy-systems': {
      id: '/articles/human-anatomy-systems'
      path: '/human-anatomy-systems'
      fullPath: '/articles/human-anatomy-systems'
      preLoaderRoute: typeof ArticlesHumanAnatomySystemsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/meiosis-gamete-formation': {
      id: '/articles/meiosis-gamete-formation'
      path: '/meiosis-gamete-formation'
      fullPath: '/articles/meiosis-gamete-formation'
      preLoaderRoute: typeof ArticlesMeiosisGameteFormationRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/mitosis-cell-division': {
      id: '/articles/mitosis-cell-division'
      path: '/mitosis-cell-division'
      fullPath: '/articles/mitosis-cell-division'
      preLoaderRoute: typeof ArticlesMitosisCellDivisionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/photosynthesis-light-reactions': {
      id: '/articles/photosynthesis-light-reactions'
      path: '/photosynthesis-light-reactions'
      fullPath: '/articles/photosynthesis-light-reactions'
      preLoaderRoute: typeof ArticlesPhotosynthesisLightReactionsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/tutorials/$slug': {
      id: '/tutorials/$slug'
      path: '/$slug'
      fullPath: '/tutorials/$slug'
      preLoaderRoute: typeof TutorialsSlugRouteImport
      parentRoute: typeof TutorialsRoute
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof VideosRoute
    }
    '/$subject/$section/$topic': {
      id: '/$subject/$section/$topic'
      path: '/$topic'
      fullPath: '/$subject/$section/$topic'
      preLoaderRoute: typeof SubjectSectionTopicRouteImport
      parentRoute: typeof SubjectSectionRoute
    }
    '/_authenticated/admin/articles': {
      id: '/_authenticated/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthenticatedAdminArticlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hero-slides': {
      id: '/_authenticated/admin/hero-slides'
      path: '/hero-slides'
      fullPath: '/admin/hero-slides'
      preLoaderRoute: typeof AuthenticatedAdminHeroSlidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/nav-links': {
      id: '/_authenticated/admin/nav-links'
      path: '/nav-links'
      fullPath: '/admin/nav-links'
      preLoaderRoute: typeof AuthenticatedAdminNavLinksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages-list': {
      id: '/_authenticated/admin/pages-list'
      path: '/pages-list'
      fullPath: '/admin/pages-list'
      preLoaderRoute: typeof AuthenticatedAdminPagesListRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections': {
      id: '/_authenticated/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AuthenticatedAdminSectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/topics': {
      id: '/_authenticated/admin/topics'
      path: '/topics'
      fullPath: '/admin/topics'
      preLoaderRoute: typeof AuthenticatedAdminTopicsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/atlas/generate': {
      id: '/api/atlas/generate'
      path: '/api/atlas/generate'
      fullPath: '/api/atlas/generate'
      preLoaderRoute: typeof ApiAtlasGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminArticlesRoute: typeof AuthenticatedAdminArticlesRoute
  AuthenticatedAdminHeroSlidesRoute: typeof AuthenticatedAdminHeroSlidesRoute
  AuthenticatedAdminNavLinksRoute: typeof AuthenticatedAdminNavLinksRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPagesListRoute: typeof AuthenticatedAdminPagesListRoute
  AuthenticatedAdminSectionsRoute: typeof AuthenticatedAdminSectionsRoute
  AuthenticatedAdminTopicsRoute: typeof AuthenticatedAdminTopicsRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminArticlesRoute: AuthenticatedAdminArticlesRoute,
  AuthenticatedAdminHeroSlidesRoute: AuthenticatedAdminHeroSlidesRoute,
  AuthenticatedAdminNavLinksRoute: AuthenticatedAdminNavLinksRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPagesListRoute: AuthenticatedAdminPagesListRoute,
  AuthenticatedAdminSectionsRoute: AuthenticatedAdminSectionsRoute,
  AuthenticatedAdminTopicsRoute: AuthenticatedAdminTopicsRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SubjectSectionRouteChildren {
  SubjectSectionTopicRoute: typeof SubjectSectionTopicRoute
}

const SubjectSectionRouteChildren: SubjectSectionRouteChildren = {
  SubjectSectionTopicRoute: SubjectSectionTopicRoute,
}

const SubjectSectionRouteWithChildren = SubjectSectionRoute._addFileChildren(
  SubjectSectionRouteChildren,
)

interface SubjectRouteChildren {
  SubjectSectionRoute: typeof SubjectSectionRouteWithChildren
}

const SubjectRouteChildren: SubjectRouteChildren = {
  SubjectSectionRoute: SubjectSectionRouteWithChildren,
}

const SubjectRouteWithChildren =
  SubjectRoute._addFileChildren(SubjectRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesCellularRespirationRoute: typeof ArticlesCellularRespirationRoute
  ArticlesEnzymeCatalysisRoute: typeof ArticlesEnzymeCatalysisRoute
  ArticlesEvolutionNaturalSelectionRoute: typeof ArticlesEvolutionNaturalSelectionRoute
  ArticlesFoodChainsEnergyFlowRoute: typeof ArticlesFoodChainsEnergyFlowRoute
  ArticlesHumanAnatomySystemsRoute: typeof ArticlesHumanAnatomySystemsRoute
  ArticlesMeiosisGameteFormationRoute: typeof ArticlesMeiosisGameteFormationRoute
  ArticlesMitosisCellDivisionRoute: typeof ArticlesMitosisCellDivisionRoute
  ArticlesPhotosynthesisLightReactionsRoute: typeof ArticlesPhotosynthesisLightReactionsRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesCellularRespirationRoute: ArticlesCellularRespirationRoute,
  ArticlesEnzymeCatalysisRoute: ArticlesEnzymeCatalysisRoute,
  ArticlesEvolutionNaturalSelectionRoute:
    ArticlesEvolutionNaturalSelectionRoute,
  ArticlesFoodChainsEnergyFlowRoute: ArticlesFoodChainsEnergyFlowRoute,
  ArticlesHumanAnatomySystemsRoute: ArticlesHumanAnatomySystemsRoute,
  ArticlesMeiosisGameteFormationRoute: ArticlesMeiosisGameteFormationRoute,
  ArticlesMitosisCellDivisionRoute: ArticlesMitosisCellDivisionRoute,
  ArticlesPhotosynthesisLightReactionsRoute:
    ArticlesPhotosynthesisLightReactionsRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface PagesRouteChildren {
  PagesSlugRoute: typeof PagesSlugRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesSlugRoute: PagesSlugRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface TutorialsRouteChildren {
  TutorialsSlugRoute: typeof TutorialsSlugRoute
}

const TutorialsRouteChildren: TutorialsRouteChildren = {
  TutorialsSlugRoute: TutorialsSlugRoute,
}

const TutorialsRouteWithChildren = TutorialsRoute._addFileChildren(
  TutorialsRouteChildren,
)

interface VideosRouteChildren {
  VideosSlugRoute: typeof VideosSlugRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosSlugRoute: VideosSlugRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SubjectRoute: SubjectRouteWithChildren,
  AiRoute: AiRoute,
  AnatomyRoute: AnatomyRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ArticlesDebugRoute: ArticlesDebugRoute,
  AtlasRoute: AtlasRoute,
  AuthRoute: AuthRoute,
  BiologicalProcessesRoute: BiologicalProcessesRoute,
  BiotechnologyRoute: BiotechnologyRoute,
  CategoriesRoute: CategoriesRoute,
  CellsMicroscopyRoute: CellsMicroscopyRoute,
  CustomListsRoute: CustomListsRoute,
  DownloadRoute: DownloadRoute,
  EcologyEnvironmentRoute: EcologyEnvironmentRoute,
  EvolutionRoute: EvolutionRoute,
  FlashcardsRoute: FlashcardsRoute,
  GeneticsDnaRoute: GeneticsDnaRoute,
  GlossaryRoute: GlossaryRoute,
  HumanBiologyRoute: HumanBiologyRoute,
  NotebookRoute: NotebookRoute,
  OrganismsRoute: OrganismsRoute,
  PagesRoute: PagesRouteWithChildren,
  PhotosyntheseRoute: PhotosyntheseRoute,
  PhotosynthesisRoute: PhotosynthesisRoute,
  PlantsRoute: PlantsRoute,
  QuizzesRoute: QuizzesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TimelineRoute: TimelineRoute,
  TutorialsRoute: TutorialsRouteWithChildren,
  VideosRoute: VideosRouteWithChildren,
  SectionTopicRoute: SectionTopicRoute,
  ApiSeedHeroSlidesRoute: ApiSeedHeroSlidesRoute,
  ApiAtlasGenerateRoute: ApiAtlasGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
