import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Loader2, ChevronDown, ChevronUp } from "lucide-react";

interface ArticleSummaryProps {
  title: string;
  content: string;
  onSummaryGenerated?: (summary: string) => void;
}

export function ArticleSummary({
  title,
  content,
  onSummaryGenerated,
}: ArticleSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateSummary = async () => {
    if (summary) {
      setIsExpanded(!isExpanded);
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      // Call server action to generate summary
      const response = await fetch("/api/summary", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title,
          content,
          maxLength: 150,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate summary");
      }

      const data = await response.json();
      setSummary(data.summary);
      setIsExpanded(true);

      if (onSummaryGenerated) {
        onSummaryGenerated(data.summary);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : "An error occurred";
      setError(message);
      console.error("Error generating summary:", err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="my-8 rounded-lg border border-blue-200 bg-blue-50 p-6">
      <div className="flex items-center justify-between gap-4">
        <div className="flex-1">
          <h3 className="mb-2 text-lg font-semibold text-blue-900">
            Quick Summary
          </h3>
          <p className="text-sm text-blue-700">
            {summary
              ? "Generated by AI — key takeaways below"
              : "Get an AI-generated summary of this article"}
          </p>
        </div>

        <Button
          onClick={handleGenerateSummary}
          disabled={isLoading}
          variant={summary ? "outline" : "default"}
          size="sm"
          className="flex items-center gap-2 whitespace-nowrap"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : summary ? (
            <>
              {isExpanded ? (
                <>
                  <ChevronUp className="h-4 w-4" />
                  Collapse
                </>
              ) : (
                <>
                  <ChevronDown className="h-4 w-4" />
                  Expand
                </>
              )}
            </>
          ) : (
            "Generate Summary"
          )}
        </Button>
      </div>

      {error && (
        <div className="mt-4 rounded bg-red-100 p-3 text-sm text-red-800">
          {error}
        </div>
      )}

      {isExpanded && summary && (
        <div className="mt-4 space-y-3 border-t border-blue-200 pt-4">
          <div className="text-sm leading-relaxed text-slate-700">
            {summary}
          </div>
          <p className="text-xs text-blue-600">
            💡 Tip: Use this summary to quickly review the main points of this
            article.
          </p>
        </div>
      )}
    </div>
  );
}
